### ISSUE TITLE
Community view object submitted without data validation

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-frontend#10]
In file pages/my/communities.vue, on form submit the data is sent to the server without any validation.
```
Lines 199-230:
    onSubmit() {
      const data = this.normalizeFormData();
      this.$store
        .dispatch('putCommunities', {
          id: this.formData.id,
          data: data
        })
        .then(() => {
          this.is_saved = true;
          setTimeout(() => {
            this.is_saved = false;
          }, 1000);
        });
    },
    /**
     * Generate the FormData
     * @returns {FormData}
     */
    normalizeFormData() {
      let data = new FormData();

      for (let item in this.formData) {
        const el = this.formData[item];
        if (el) {
          if (Array.isArray(el)) {
            data.append(item, JSON.stringify(el));
          } else {
            let ElValue = el ? el : null;
            data.append(item, ElValue);
          }
        }
      }
```
Mitigatioin: The form input fields need to be checked, as explained in the article:
https://vuejs.org/v2/cookbook/form-validation.html
The URLs should be validated for protocol, server and route
The file URLs should check for type and size of file

**Comment by mahesh-cybsec** [comment]
The PR number is not specified in the issue for a quick diff verification. Which version should I download to verify the fix?

**Comment by YuriiDunaev** [comment]
You can check this commit https://github.com/surfedushare/surf-frontend/commit/3d19c3d15de04ed3e735d9a34f528510cf41bd9b or this file https://github.com/surfedushare/surf-frontend/blob/master/pages/my/communities.vue

**Comment by mahesh-cybsec** [comment]
Specified commit reviewed. The fix is adequate. Verified.

**Comment by sveeke** [comment]
Okay, then I'll close this issue.
