### ISSUE TITLE
Missing X-XSS-Protection header

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-frontend#13]
This needs to be fixed on the production environment.

The X-XSS-Protection header is not set by the application in the HTTP responses.

The X-XSS-Protection HTTP Header is not set. This header enables the Cross-Site Scripting (XSS) filter built into most recent web browsers. By setting the X-XSS-Protection header the browser is instructed to not render the page if an XSS attack is detected. It is therefore a client-side defense mechanism.

### Affected URL(s):
+ https://surf.stg.mqd.me/api/v1/*
+ https://surfcatalog.firebaseapp.com/

### Impact
Disabling (not using) this option increases the attack surface for XSS attacks.

### Recommendation
Add the following HTTP header to all server responses: X-XSS-Protection: 1; mode=block. For more information visit https://www.owasp.org/index.php/OWASP_Secure_Headers_Project

**Comment by sveeke** [comment]
This should be fixed in the SURF production environment.

**Comment by abhinavmishra-ros** [comment]
> This should be fixed in the SURF production environment.

This issue can be considered as fixed.

**Comment by sveeke** [comment]
Indeed, I'll close it.
