### ISSUE TITLE
Input returned in response (Possible Cross site scripting)

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-frontend#15]
Two instances in the application were discovered where the user input was returned in the application response. Though the content type is JSON hence, no XSS execution was possible.

### Affected Endpoints:
+ /api/v1/collections/ad83a147-7360-4626-8aa2-3ba22f26fcaf/ [title JSON parameter]
+ /api/v1/materials/rating/ [object_id JSON parameter]

### Impact
Currently this does not posses any direct security issue to the application, but this may lead to cross site scripting attacks if the data returned in JSON response is used as it is in the HTML context.

### Recommendation
Output encoding should be applied everywhere the user input is being returned as a part of HTTP response.

**Comment by ggevorg** [comment]
I added output encoding (escaping) for these endpoints.

**Comment by abhinavmishra-ros** [comment]
Output encoding fixes the issue. Thanks.

**Comment by sveeke** [comment]
I'll close the issue then.
