### ISSUE TITLE
Files of arbitrary type and unmimitrd size can be uploaded

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-frontend#2]
In file, InputFile/InputFile.component.js, lines 39-48:
```
createImage(file) {
      let image = new Image();
      let reader = new FileReader();
      let that = this;

      reader.onload = e => {
        that.image = e.target.result;
      };
      reader.readAsDataURL(file);
    }
```
The (image) file or URL to be read is not checked for type or size validation. This may potentially lead to arbitrary file upload, or arbitrary image resource access if remote URL is specified.

**Comment by YuriiDunaev** [comment]
Added validation

**Comment by sveeke** [comment]
> Added validation

Awesome. In what commit? I'll gather those so the auditors can more easily verify the changes to the code.

**Comment by YuriiDunaev** [comment]
https://github.com/surfedushare/surf-frontend/commit/3d19c3d15de04ed3e735d9a34f528510cf41bd9b

**Comment by mahesh-cybsec** [comment]
Verified.

**Comment by sveeke** [comment]
Awesome, closed.
