### ISSUE TITLE
Inadequate input validation in materials.js

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-frontend#5]
In file store/modules/materials.js, multiple web requests are made through axios component by embedding API routes and parameters with user supplied or selected data.
```
Line 40:      const material = await this.$axios.$get(`materials/${id}/`);

Line 47:      const material = await this.$axios.$get(`materials/${id}/`, { params });

Line 54:      const material = await this.$axios.$get(`materials/`, { params });

Line 62:      const communities = await this.$axios.$get('communities/', { params });

Line 66:      return await this.$axios.$post('materials/rating/', rating);

Line 69:      return await this.$axios.$get('materials/rating/', {
        params: {
          object_id: id
        }

Line 76:       return await this.$axios.$post('applaud-materials/', {
        material: {
          external_id: external_id
        }

Line 83:       return await this.$axios.$get('applaud-materials/', {
        params: {
          material__external_id: external_id  // Mahesh validate external_id
        }
```

For the following search APIs calls, potentially the search string is displayed along with the results, which may lead to XSS, apart from the search query injection attacks on the server if the server does not perform adequate validation or convert the search strings to literal strings (or httpEncode the search string).
 
```
Line 91:       const materials = await this.$axios.$post('materials/search/', search);

Line 102:      const materials = await this.$axios.$post(
        `communities/${id}/search/`,
        search

Line 116:      const materials = await this.$axios.$post('materials/search/', search)
               commit('SET_NEXT_PAGE_MATERIALS', materials);

Line 130:      const keywords = await this.$axios.$get('keywords/', { params });
               commit('SET_MATERIALS_KEYWORDS', keywords);


```
The values of id, data and params should be validated before submitting to the server, and value of the search results should be "quoted" / safely encoded before committing the server response to display, to avoid XSS vulnerability.

The case of "post" APIs, which potentially change the server state and/or data, validation is of higher importance.

https://vuejsexamples.com/tag/validation/ for more information on how to perform data validation,

**Comment by YuriiDunaev** [comment]
https://github.com/surfedushare/surf-frontend/commit/7a763d7784ae7e526d47be1fbb15988ec963dc58 updated validation. Can you check?

**Comment by mahesh-cybsec** [comment]
As pointed out in the issue description, the data validation has been applied. Specific validation helper methods are referenced - for string, ID,base64 and search string. The fix appears to be adequate.

**Comment by sveeke** [comment]
I'll close it then.
