### ISSUE TITLE
Inadequate input validation in themes.js

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-frontend#7]
In file store/modules/themes.js, multiple web requests are made through axios component by embedding API routes and parameters with user supplied or selected data.
```
Line 34:      const theme = await this.$axios.$get(`themes/${id}`); 
Line 39:      const themeDisciplines = await this.$axios.$get( 
        `themes/${id}/disciplines`);
Line 45:      const themeCommunities = await this.$axios.$get(
        `themes/${id}/communities`,
        { params }      );
Line 52:      const themeCollections = await this.$axios.$get(
        `themes/${id}/community-collections`       );
```
The values of id should be validated before submitting to the server.
https://vuejsexamples.com/tag/validation/ for more information on how to perform data validation,

**Comment by YuriiDunaev** [comment]
Thank you for feedback, @sveeke . Can you give more information about how it might not be safe? For example, a link to the dock.

**Comment by mahesh-cybsec** [comment]
As a result of the ${id} being under the control of the user (through dropdown, checkbox, or clicking specific icon,and in case of an attacker, through tools such as tamperdata browser helper), the value of the id is untrusted. The frontend should contain a whitelist of theme ids supplied by the server and match the value against this list, on making the server API call.

The value of id is probably used on the server to either fetch a resource file, or create a property file to download to the frontend, or lookup in the DB, etc. This can lead to potentially execute OS command (in case of file access) or DB query injection (in case of DB look up), or stored attack vector (property file creation), etc.

**Comment by YuriiDunaev** [comment]
> The frontend should contain a whitelist of theme ids supplied by the server and match the value against this list, on making the server API call.
Whitelist ids are large and dynamic for all API items. Maybe, backend validation is enough?

**Comment by mahesh-cybsec** [comment]
Suggested validation would be:
- theme id length
- theme id content - alphanumeric

**Comment by mahesh-cybsec** [comment]
Similar validation is suggested for other issues as well.

**Comment by YuriiDunaev** [comment]
@mahesh-cybsec  https://github.com/surfedushare/surf-frontend/commit/4a1c0aeef8e60387ec4532a58c3b337bee99dad4 check it, please

**Comment by mahesh-cybsec** [comment]
Helper function to validate ID string added This function is invoked at the stated places. The fix appears to be adequate.

**Comment by sveeke** [comment]
I'll close it then.
