### ISSUE TITLE
Inadequate input validation in filters.js

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-frontend#8]
In file store/modules/filters.js, multiple web requests are made through axios component by embedding API routes and parameters with user supplied or selected data.
```
Line 29:
        const filter = await this.$axios.$get(`filters/${id}/`);
Line 37:
      const filter = await this.$axios.$post(`filters/`, data);

Line 41:
      const filter = await this.$axios.$put(`filters/${data.id}/`, data);

Line 47:
      await this.$axios.$delete(`filters/${id}/`);
Line 53:
        const filter = await this.$axios.$get(`filters/${id}/`);
```
The values of id and data should be validated before submitting to the server.

https://vuejsexamples.com/tag/validation/ for more information on how to perform data validation,

**Comment by YuriiDunaev** [comment]
https://github.com/surfedushare/surf-frontend/commit/2f2248ea3555e411a9888363b77be7b0212814b2 check, please

**Comment by mahesh-cybsec** [comment]
Fix uses data validation helper classes. Appears to be adequate validation is now applied. Confirmed the fix.

**Comment by sveeke** [comment]
I'll close it then.
