### ISSUE TITLE
Inadequate input validation in communities.js

### ISSUE THREAD

**Issue by sveeke** [surfedushare/surf-frontend#9]
In file store/modules/communities.js , multiple web requests are made through axios component by embedding API routes and parameters with user supplied or selected data.
```
Lines 32-60:

 actions: {
    async putCommunities({ commit }, { id, data = {} } = {}) {
         const communities = await this.$axios.$put(`communities/${id}/`, data);
...
...

    async getCommunity({ commit }, id) {
      const community_info = await this.$axios.$get(`communities/${id}/`);
...
...
    async getCommunityThemes({ commit }, id) { 
      const community_themes = await this.$axios.$get(
        `communities/${id}/themes/`
      );
   
...
...
    async getCommunityDisciplines({ commit }, id) {
      const community_disciplines = await this.$axios.$get(
        `communities/${id}/disciplines/`      );
...
...
    async getCommunityCollections({ commit }, id) {
      const community_collections = await this.$axios.$get(
        `communities/${id}/collections/`
...
...
  }
```
The values of id and data should be validated before submitting to the server.

https://vuejsexamples.com/tag/validation/ for more information on how to perform data validation,

**Comment by YuriiDunaev** [comment]
https://github.com/surfedushare/surf-frontend/commit/ece878b7d8799abb1212112c48428b8c5d572a23 check, please

**Comment by mahesh-cybsec** [comment]
Fix uses data validation helper classes. Appears to be adequate validation is now applied. Confirmed the fix.

**Comment by sveeke** [comment]
Awesome, I'll close it then.
